name: "tfvdc-actions"
description: "Check description is included in Terraform variable blocks"
author: tsubasaogawa

inputs:
  input_path:
    description: "Input directory path"
    required: false
    default: "."
  result_path:
    description: "Result file path"
    required: false
    default: "~/tfvdc.out"

runs:
  using: "composite"
  steps:
    - name: Download tfvdc
      env:
        BIN_URL: https://github.com/tsubasaogawa/terraform-variable-description-coverage/releases/latest/download/tfvdc_linux_x86_64.tar.gz
      run: |
        curl -L --silent $BIN_URL | tar zx -O tfvdc > ~/tfvdc
        chmod 755 ~/tfvdc
      shell: bash
    - name: Run tfvdc
      run: |
        ~/tfvdc ${{ inputs.input_path }} 2>&1 1>/dev/null | tee ${{ inputs.result_path }}
      shell: bash

branding:
  icon: "check-circle"
  color: "green"
