name: tfvdc

on: [pull_request]

jobs:
  tfvdc:
    name: tfvdc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download tfvdc
        run: |
          curl -L --silent https://github.com/tsubasaogawa/terraform-variable-description-coverage/releases/latest/download/tfvdc_linux_x86_64.tar.gz | tar zx -O tfvdc > /usr/bin/tfvdc
          chmod 755 /usr/bin/tfvdc
      - name: Run
        run: /usr/bin/tfvdc > ./tfvdc.out
