name: tfvdc

on: [pull_request]

jobs:
  tfvdc:
    name: tfvdc
    runs-on: ubuntu-latest
    env:
      checkout_dirname: tfdir
      output_filename: tfvdc.out
    steps:
      - uses: actions/checkout@v3
        with:
          path: "tfdir"
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - uses: tsubasaohawa/tfvdc-actions@v1
        with:
          input_path: ${{ github.workspace }}/${{ env.checkout_dirname }}
          output_path: ${{ github.workspace }}/${{ env.output_filename }}
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ${{ github.workspace }}/${{ env.output_filename }} | reviewdog -reporter=github-pr-review -f=golint
